version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    depends_on:
      - postgres

  postgres:
    container_name: yii2postgres
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_ROOT_PASSWORD: "root"
      POSTGRES_DB: "root"
    ports:
      - '5432:5432'
